### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by grozen** [cyclejs-community/cycle-delayed-driver#3]
This includes a "compilation" task in package.json.

**Comment by grozen** [comment]
Done as of 807ca2fdbd120c56dbd4c1b9abe63cb8f9ecaf20.

**Comment by Widdershin** [comment]
Congratulations on your first release @grozen! 🎉 😸

**Comment by grozen** [comment]
Thank you very much, @Widdershin 😄 
Even if it doesn't help anyone tackle the somewhat uncommon problem it solves, at least I learned a whole lot doing it.
